### ISSUE TITLE
Нельзя создать ссессию и отсутвует .env-example

### ISSUE THREAD

**Issue by andreidevs** [Re-Diss/IcebergAppBot#1]
![изображение](https://github.com/Re-Diss/IcebergAppBot/assets/57400388/fe491e72-138b-481b-879b-afd10fb6cf1f)

**Comment by Re-Diss** [comment]
сорян, вчера поздно выкатил, забыл readme поправить. Сделай git pull и еще раз проверь. Я там немного логику поменял, теперь не надо файл .env а все настройки в config.py
Но думаю наверное верну назад его

**Comment by andreidevs** [comment]
Все равно не дает создать ссесию, там не дает выбрать 3 пункт

> сорян, вчера поздно выкатил, забыл readme поправить. Сделай git pull и еще раз проверь. Я там немного логику поменял, теперь не надо файл .env а все настройки в config.py Но думаю наверное верну назад его

**Comment by Re-Diss** [comment]
> Все равно не дает создать ссесию, там не дает выбрать 3 пункт
> 
> > сорян, вчера поздно выкатил, забыл readme поправить. Сделай git pull и еще раз проверь. Я там немного логику поменял, теперь не надо файл .env а все настройки в config.py Но думаю наверное верну назад его

попробуй удали папку с ботом и заново склонируй
